# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.TextField(max_length=1000)),
                ('comment', models.TextField(max_length=1000)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(related_name='user', to='User.User')),
            ],
        ),
    ]
